// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.5
// source: attendservice.proto

package attendservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PullAttRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SupervisorID string  `protobuf:"bytes,1,opt,name=SupervisorID,proto3" json:"SupervisorID,omitempty"`
	Longitude    float32 `protobuf:"fixed32,2,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	Latitude     float32 `protobuf:"fixed32,3,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	CourseID     string  `protobuf:"bytes,4,opt,name=CourseID,proto3" json:"CourseID,omitempty"`
}

func (x *PullAttRequest) Reset() {
	*x = PullAttRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attendservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullAttRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullAttRequest) ProtoMessage() {}

func (x *PullAttRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullAttRequest.ProtoReflect.Descriptor instead.
func (*PullAttRequest) Descriptor() ([]byte, []int) {
	return file_attendservice_proto_rawDescGZIP(), []int{0}
}

func (x *PullAttRequest) GetSupervisorID() string {
	if x != nil {
		return x.SupervisorID
	}
	return ""
}

func (x *PullAttRequest) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *PullAttRequest) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *PullAttRequest) GetCourseID() string {
	if x != nil {
		return x.CourseID
	}
	return ""
}

type AttResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  uint32 `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Error   string `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *AttResponse) Reset() {
	*x = AttResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attendservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttResponse) ProtoMessage() {}

func (x *AttResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attendservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttResponse.ProtoReflect.Descriptor instead.
func (*AttResponse) Descriptor() ([]byte, []int) {
	return file_attendservice_proto_rawDescGZIP(), []int{1}
}

func (x *AttResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AttResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AttResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_attendservice_proto protoreflect.FileDescriptor

var file_attendservice_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x22, 0x8a, 0x01, 0x0a, 0x0e, 0x50, 0x75, 0x6c, 0x6c, 0x41, 0x74, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x53, 0x75, 0x70, 0x65, 0x72,
	0x76, 0x69, 0x73, 0x6f, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x53,
	0x75, 0x70, 0x65, 0x72, 0x76, 0x69, 0x73, 0x6f, 0x72, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x4c,
	0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09,
	0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x4c, 0x61, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49,
	0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49,
	0x44, 0x22, 0x55, 0x0a, 0x0b, 0x41, 0x74, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x5c, 0x0a, 0x0d, 0x41, 0x74, 0x74, 0x65,
	0x6e, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x0e, 0x50, 0x75, 0x6c,
	0x6c, 0x41, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1d, 0x2e, 0x61, 0x74,
	0x74, 0x65, 0x6e, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x75, 0x6c, 0x6c,
	0x41, 0x74, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x74, 0x74,
	0x65, 0x6e, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x74, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x61, 0x74, 0x74, 0x65,
	0x6e, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_attendservice_proto_rawDescOnce sync.Once
	file_attendservice_proto_rawDescData = file_attendservice_proto_rawDesc
)

func file_attendservice_proto_rawDescGZIP() []byte {
	file_attendservice_proto_rawDescOnce.Do(func() {
		file_attendservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_attendservice_proto_rawDescData)
	})
	return file_attendservice_proto_rawDescData
}

var file_attendservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_attendservice_proto_goTypes = []interface{}{
	(*PullAttRequest)(nil), // 0: attendservice.PullAttRequest
	(*AttResponse)(nil),    // 1: attendservice.AttResponse
}
var file_attendservice_proto_depIdxs = []int32{
	0, // 0: attendservice.Attendservice.PullAttendance:input_type -> attendservice.PullAttRequest
	1, // 1: attendservice.Attendservice.PullAttendance:output_type -> attendservice.AttResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_attendservice_proto_init() }
func file_attendservice_proto_init() {
	if File_attendservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_attendservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullAttRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_attendservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_attendservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_attendservice_proto_goTypes,
		DependencyIndexes: file_attendservice_proto_depIdxs,
		MessageInfos:      file_attendservice_proto_msgTypes,
	}.Build()
	File_attendservice_proto = out.File
	file_attendservice_proto_rawDesc = nil
	file_attendservice_proto_goTypes = nil
	file_attendservice_proto_depIdxs = nil
}
