// Code generated by goctl. DO NOT EDIT.
package types

type PullAttRequest struct {
	SupervisorID string  `json:"supervisor_id" form:"supervisor_id"`
	Longitude    float64 `json:"longitude" form:"longitude"`
	Latitude     float64 `json:"latitude" form:"latitude"`
	CourseID     string  `json:"course_id" form:"course_id"`
}

type AttResponse struct {
	Status  uint32      `json:"status"`
	Data    interface{} `json:"data"`
	Total   uint32      `json:"total"`
	Message string      `json:"message"`
	Error   string      `json:"error"`
}

type NormalAttReq struct {
	CourseID     string `json:"course_id"`
	SupervisroID string `json:"supervisor_id"`
	StudentID    string `json:"student_id"`
	University   string `json:"university"`
	CourseMain   int64  `json:"course_main"`
	Type         uint   `json:"type"`
}

type LocationAttReq struct {
	StudentID    string  `json:"student_id"`
	CourseMain   int64   `json:"course_main"`
	SupervisorID string  `json:"supervisor_id"`
	Longitude    float64 `json:"longitude"`
	Latitude     float64 `json:"latitude"`
}

type GetAttListByCourseReq struct {
	CourseMain uint64 `json:"course_main" form:"course_main"`
	Week       uint32 `json:"week" form:"week"`
}
