// Code generated by goctl. DO NOT EDIT.
package types

type PullAttRequest struct {
	SupervisorID string  `json:"supervisor_id" form:"supervisor_id"`
	Longitude    float64 `json:"longitude" form:"longitude"`
	Latitude     float64 `json:"latitude" form:"latitude"`
	CourseID     string  `json:"course_id" form:"course_id"`
}

type AttResponse struct {
	Status  uint32 `json:"status"`
	Message string `json:"message"`
	Error   string `json:"error"`
}
