// Code generated by goctl. DO NOT EDIT.
// Source: mq.proto

package server

import (
	"context"

	"mq_server/internal/logic"
	"mq_server/internal/svc"
	"mq_server/mq"
)

type MqServer struct {
	svcCtx *svc.ServiceContext
	mq.UnimplementedMqServer
}

func NewMqServer(svcCtx *svc.ServiceContext) *MqServer {
	return &MqServer{
		svcCtx: svcCtx,
	}
}

func (s *MqServer) Publish(ctx context.Context, in *mq.Request) (*mq.Response, error) {
	l := logic.NewPublishLogic(ctx, s.svcCtx)
	return l.Publish(in)
}

func (s *MqServer) PublishLeave(ctx context.Context, in *mq.LeaveRequest) (*mq.Response, error) {
	l := logic.NewPublishLeaveLogic(ctx, s.svcCtx)
	return l.PublishLeave(in)
}

func (s *MqServer) PublishPull(ctx context.Context, in *mq.AttRequest) (*mq.Response, error) {
	l := logic.NewPublishPullLogic(ctx, s.svcCtx)
	return l.PublishPull(in)
}
