// Code generated by goctl. DO NOT EDIT.
package types

type AppealRequest struct {
	StudentID       uint64 `json:"student_id,omitempty" form:"student_id"`
	ContactPhone    string `json:"contact_phone,omitempty" form:"contact_phone"`
	EmergencyName   string `json:"emergency_name,omitempty" form:"emergency_name"`
	EmergencyPhone  string `json:"emergency_phone,omitempty" form:"emergency_phone"`
	CounsellorName  string `json:"counsellor_name,omitempty" form:"counsellor_name"`
	CounsellorID    uint64 `json:"counsellor_id,omitempty" form:"counsellor_id"`
	LeaveReason     string `json:"reason" form:"reason"`
	CourseName      string `json:"course_name" form:"course_name"`
	CourseID        uint64 `json:"course_id" form:"course_id"`
	LeaveCourseFrom int    `json:"lea_from" form:"lea_from"`
	LeaveCourseTo   int    `json:"lea_to" form:"lea_to"`
	TagAs           uint   `json:"tag" form:"tag"` //默认为请假条
}

type AppealListRequest struct {
	StudentID uint64 `json:"student_id" form:"student_id"`
}

type ListReply struct {
	Status  uint32      `json:"status"`
	Message string      `json:"msg"`
	Data    interface{} `json:"data"`
	Total   uint32      `json:"total"`
	Error   string      `json:"error"`
}

type AppealResponse struct {
	Status  uint32 `json:"status"`
	Message string `json:"msg"`
	Error   string `json:"error"`
}
