// Code generated by goctl. DO NOT EDIT.
// Source: attendinfo.proto

package server

import (
	"context"

	"info/attendinfo"
	"info/internal/logic"
	"info/internal/svc"
)

type AttendinfoServer struct {
	svcCtx *svc.ServiceContext
	attendinfo.UnimplementedAttendinfoServer
}

func NewAttendinfoServer(svcCtx *svc.ServiceContext) *AttendinfoServer {
	return &AttendinfoServer{
		svcCtx: svcCtx,
	}
}

func (s *AttendinfoServer) GetCourseAttInfo(ctx context.Context, in *attendinfo.CourseInfoRequest) (*attendinfo.CourseInfoResponse, error) {
	l := logic.NewGetCourseAttInfoLogic(ctx, s.svcCtx)
	return l.GetCourseAttInfo(in)
}

func (s *AttendinfoServer) GetCounsellorAttInfo(ctx context.Context, in *attendinfo.CounsellorAttInfoReq) (*attendinfo.CounsellorAttInfoRsp, error) {
	l := logic.NewGetCounsellorAttInfoLogic(ctx, s.svcCtx)
	return l.GetCounsellorAttInfo(in)
}
