// Code generated by goctl. DO NOT EDIT.
// Source: appealservice.proto

package server

import (
	"context"

	"appeal-gateway/rpc/appeal/appeal"
	"appeal-gateway/rpc/appeal/internal/logic"
	"appeal-gateway/rpc/appeal/internal/svc"
)

type AppealServer struct {
	svcCtx *svc.ServiceContext
	appeal.UnimplementedAppealServer
}

func NewAppealServer(svcCtx *svc.ServiceContext) *AppealServer {
	return &AppealServer{
		svcCtx: svcCtx,
	}
}

func (s *AppealServer) StudentAskforLeave(ctx context.Context, in *appeal.AppealRequest) (*appeal.AppealResponse, error) {
	l := logic.NewStudentAskforLeaveLogic(ctx, s.svcCtx)
	return l.StudentAskforLeave(in)
}

func (s *AppealServer) GetAppealListBySid(ctx context.Context, in *appeal.AppealListRequset) (*appeal.AppealListReply, error) {
	l := logic.NewGetAppealListBySidLogic(ctx, s.svcCtx)
	return l.GetAppealListBySid(in)
}
