// Code generated by goctl. DO NOT EDIT.
// Source: attendinfo.proto

package attendinfoclient

import (
	"context"

	"info/attendinfo"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CounsellorAttInfoReq = attendinfo.CounsellorAttInfoReq
	CounsellorAttInfoRsp = attendinfo.CounsellorAttInfoRsp
	CourseAttInfo        = attendinfo.CourseAttInfo
	CourseInfoRequest    = attendinfo.CourseInfoRequest
	CourseInfoResponse   = attendinfo.CourseInfoResponse
	CourseRate           = attendinfo.CourseRate
	MajorRate            = attendinfo.MajorRate
	MajorReqList         = attendinfo.MajorReqList
	UnpresentModel       = attendinfo.UnpresentModel

	Attendinfo interface {
		GetCourseAttInfo(ctx context.Context, in *CourseInfoRequest, opts ...grpc.CallOption) (*CourseInfoResponse, error)
		GetCounsellorAttInfo(ctx context.Context, in *CounsellorAttInfoReq, opts ...grpc.CallOption) (*CounsellorAttInfoRsp, error)
	}

	defaultAttendinfo struct {
		cli zrpc.Client
	}
)

func NewAttendinfo(cli zrpc.Client) Attendinfo {
	return &defaultAttendinfo{
		cli: cli,
	}
}

func (m *defaultAttendinfo) GetCourseAttInfo(ctx context.Context, in *CourseInfoRequest, opts ...grpc.CallOption) (*CourseInfoResponse, error) {
	client := attendinfo.NewAttendinfoClient(m.cli.Conn())
	return client.GetCourseAttInfo(ctx, in, opts...)
}

func (m *defaultAttendinfo) GetCounsellorAttInfo(ctx context.Context, in *CounsellorAttInfoReq, opts ...grpc.CallOption) (*CounsellorAttInfoRsp, error) {
	client := attendinfo.NewAttendinfoClient(m.cli.Conn())
	return client.GetCounsellorAttInfo(ctx, in, opts...)
}
