// Code generated by goctl. DO NOT EDIT.
// Source: attendservice.proto

package server

import (
	"context"

	"attendance-gateway/rpc/attend/attendservice"
	"attendance-gateway/rpc/attend/internal/logic"
	"attendance-gateway/rpc/attend/internal/svc"
)

type AttendserviceServer struct {
	svcCtx *svc.ServiceContext
	attendservice.UnimplementedAttendserviceServer
}

func NewAttendserviceServer(svcCtx *svc.ServiceContext) *AttendserviceServer {
	return &AttendserviceServer{
		svcCtx: svcCtx,
	}
}

func (s *AttendserviceServer) PullAttendance(ctx context.Context, in *attendservice.PullAttRequest) (*attendservice.AttResponse, error) {
	l := logic.NewPullAttendanceLogic(ctx, s.svcCtx)
	return l.PullAttendance(in)
}
