// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.2.0
// source: attendinfo.proto

package attendinfo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CourseInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	University  string `protobuf:"bytes,1,opt,name=University,proto3" json:"University,omitempty"`
	Courseid    string `protobuf:"bytes,2,opt,name=Courseid,proto3" json:"Courseid,omitempty"`
	Course_Main uint32 `protobuf:"varint,3,opt,name=Course_Main,json=CourseMain,proto3" json:"Course_Main,omitempty"`
}

func (x *CourseInfoRequest) Reset() {
	*x = CourseInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attendinfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourseInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseInfoRequest) ProtoMessage() {}

func (x *CourseInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendinfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseInfoRequest.ProtoReflect.Descriptor instead.
func (*CourseInfoRequest) Descriptor() ([]byte, []int) {
	return file_attendinfo_proto_rawDescGZIP(), []int{0}
}

func (x *CourseInfoRequest) GetUniversity() string {
	if x != nil {
		return x.University
	}
	return ""
}

func (x *CourseInfoRequest) GetCourseid() string {
	if x != nil {
		return x.Courseid
	}
	return ""
}

func (x *CourseInfoRequest) GetCourse_Main() uint32 {
	if x != nil {
		return x.Course_Main
	}
	return 0
}

type CourseInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status         uint32           `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message        string           `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	CourseAttInfos []*CourseAttInfo `protobuf:"bytes,3,rep,name=CourseAttInfos,proto3" json:"CourseAttInfos,omitempty"`
	Total          uint32           `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Error          string           `protobuf:"bytes,5,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *CourseInfoResponse) Reset() {
	*x = CourseInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attendinfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourseInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseInfoResponse) ProtoMessage() {}

func (x *CourseInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attendinfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseInfoResponse.ProtoReflect.Descriptor instead.
func (*CourseInfoResponse) Descriptor() ([]byte, []int) {
	return file_attendinfo_proto_rawDescGZIP(), []int{1}
}

func (x *CourseInfoResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CourseInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CourseInfoResponse) GetCourseAttInfos() []*CourseAttInfo {
	if x != nil {
		return x.CourseAttInfos
	}
	return nil
}

func (x *CourseInfoResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CourseInfoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CourseAttInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Week           uint32            `protobuf:"varint,1,opt,name=Week,proto3" json:"Week,omitempty"`
	AttendRate     float64           `protobuf:"fixed64,2,opt,name=AttendRate,proto3" json:"AttendRate,omitempty"`
	UnpresentCount uint32            `protobuf:"varint,3,opt,name=UnpresentCount,proto3" json:"UnpresentCount,omitempty"`
	UnpresentInfos []*UnpresentModel `protobuf:"bytes,4,rep,name=UnpresentInfos,proto3" json:"UnpresentInfos,omitempty"` //返回缺勤人信息
}

func (x *CourseAttInfo) Reset() {
	*x = CourseAttInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attendinfo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourseAttInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseAttInfo) ProtoMessage() {}

func (x *CourseAttInfo) ProtoReflect() protoreflect.Message {
	mi := &file_attendinfo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseAttInfo.ProtoReflect.Descriptor instead.
func (*CourseAttInfo) Descriptor() ([]byte, []int) {
	return file_attendinfo_proto_rawDescGZIP(), []int{2}
}

func (x *CourseAttInfo) GetWeek() uint32 {
	if x != nil {
		return x.Week
	}
	return 0
}

func (x *CourseAttInfo) GetAttendRate() float64 {
	if x != nil {
		return x.AttendRate
	}
	return 0
}

func (x *CourseAttInfo) GetUnpresentCount() uint32 {
	if x != nil {
		return x.UnpresentCount
	}
	return 0
}

func (x *CourseAttInfo) GetUnpresentInfos() []*UnpresentModel {
	if x != nil {
		return x.UnpresentInfos
	}
	return nil
}

type UnpresentModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code       string `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	MissAttend uint32 `protobuf:"varint,3,opt,name=MissAttend,proto3" json:"MissAttend,omitempty"` //1缺勤，2.出勤
}

func (x *UnpresentModel) Reset() {
	*x = UnpresentModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attendinfo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnpresentModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpresentModel) ProtoMessage() {}

func (x *UnpresentModel) ProtoReflect() protoreflect.Message {
	mi := &file_attendinfo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpresentModel.ProtoReflect.Descriptor instead.
func (*UnpresentModel) Descriptor() ([]byte, []int) {
	return file_attendinfo_proto_rawDescGZIP(), []int{3}
}

func (x *UnpresentModel) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UnpresentModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UnpresentModel) GetMissAttend() uint32 {
	if x != nil {
		return x.MissAttend
	}
	return 0
}

type CounsellorAttInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MajorList []*MajorReqList `protobuf:"bytes,1,rep,name=MajorList,proto3" json:"MajorList,omitempty"`
}

func (x *CounsellorAttInfoReq) Reset() {
	*x = CounsellorAttInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attendinfo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CounsellorAttInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounsellorAttInfoReq) ProtoMessage() {}

func (x *CounsellorAttInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_attendinfo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounsellorAttInfoReq.ProtoReflect.Descriptor instead.
func (*CounsellorAttInfoReq) Descriptor() ([]byte, []int) {
	return file_attendinfo_proto_rawDescGZIP(), []int{4}
}

func (x *CounsellorAttInfoReq) GetMajorList() []*MajorReqList {
	if x != nil {
		return x.MajorList
	}
	return nil
}

type MajorReqList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Major      string   `protobuf:"bytes,1,opt,name=Major,proto3" json:"Major,omitempty"`
	University string   `protobuf:"bytes,2,opt,name=University,proto3" json:"University,omitempty"`
	CouseMain  []uint64 `protobuf:"varint,3,rep,packed,name=CouseMain,proto3" json:"CouseMain,omitempty"`
}

func (x *MajorReqList) Reset() {
	*x = MajorReqList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attendinfo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MajorReqList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MajorReqList) ProtoMessage() {}

func (x *MajorReqList) ProtoReflect() protoreflect.Message {
	mi := &file_attendinfo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MajorReqList.ProtoReflect.Descriptor instead.
func (*MajorReqList) Descriptor() ([]byte, []int) {
	return file_attendinfo_proto_rawDescGZIP(), []int{5}
}

func (x *MajorReqList) GetMajor() string {
	if x != nil {
		return x.Major
	}
	return ""
}

func (x *MajorReqList) GetUniversity() string {
	if x != nil {
		return x.University
	}
	return ""
}

func (x *MajorReqList) GetCouseMain() []uint64 {
	if x != nil {
		return x.CouseMain
	}
	return nil
}

type CounsellorAttInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status         uint32        `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message        string        `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	MajorRateList  []*MajorRate  `protobuf:"bytes,3,rep,name=MajorRateList,proto3" json:"MajorRateList,omitempty"`
	CourseRateList []*CourseRate `protobuf:"bytes,4,rep,name=CourseRateList,proto3" json:"CourseRateList,omitempty"` //返回前十个
	Total1         uint32        `protobuf:"varint,5,opt,name=Total1,proto3" json:"Total1,omitempty"`
	Total2         uint32        `protobuf:"varint,6,opt,name=Total2,proto3" json:"Total2,omitempty"`
}

func (x *CounsellorAttInfoRsp) Reset() {
	*x = CounsellorAttInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attendinfo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CounsellorAttInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounsellorAttInfoRsp) ProtoMessage() {}

func (x *CounsellorAttInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_attendinfo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounsellorAttInfoRsp.ProtoReflect.Descriptor instead.
func (*CounsellorAttInfoRsp) Descriptor() ([]byte, []int) {
	return file_attendinfo_proto_rawDescGZIP(), []int{6}
}

func (x *CounsellorAttInfoRsp) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CounsellorAttInfoRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CounsellorAttInfoRsp) GetMajorRateList() []*MajorRate {
	if x != nil {
		return x.MajorRateList
	}
	return nil
}

func (x *CounsellorAttInfoRsp) GetCourseRateList() []*CourseRate {
	if x != nil {
		return x.CourseRateList
	}
	return nil
}

func (x *CounsellorAttInfoRsp) GetTotal1() uint32 {
	if x != nil {
		return x.Total1
	}
	return 0
}

func (x *CounsellorAttInfoRsp) GetTotal2() uint32 {
	if x != nil {
		return x.Total2
	}
	return 0
}

type MajorRate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Major      string  `protobuf:"bytes,1,opt,name=Major,proto3" json:"Major,omitempty"`
	AttendRate float64 `protobuf:"fixed64,2,opt,name=AttendRate,proto3" json:"AttendRate,omitempty"`
}

func (x *MajorRate) Reset() {
	*x = MajorRate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attendinfo_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MajorRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MajorRate) ProtoMessage() {}

func (x *MajorRate) ProtoReflect() protoreflect.Message {
	mi := &file_attendinfo_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MajorRate.ProtoReflect.Descriptor instead.
func (*MajorRate) Descriptor() ([]byte, []int) {
	return file_attendinfo_proto_rawDescGZIP(), []int{7}
}

func (x *MajorRate) GetMajor() string {
	if x != nil {
		return x.Major
	}
	return ""
}

func (x *MajorRate) GetAttendRate() float64 {
	if x != nil {
		return x.AttendRate
	}
	return 0
}

type CourseRate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CourseMain uint64  `protobuf:"varint,1,opt,name=CourseMain,proto3" json:"CourseMain,omitempty"`
	AttendRate float64 `protobuf:"fixed64,2,opt,name=AttendRate,proto3" json:"AttendRate,omitempty"`
	Week       int32   `protobuf:"varint,3,opt,name=Week,proto3" json:"Week,omitempty"`
}

func (x *CourseRate) Reset() {
	*x = CourseRate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attendinfo_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourseRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseRate) ProtoMessage() {}

func (x *CourseRate) ProtoReflect() protoreflect.Message {
	mi := &file_attendinfo_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseRate.ProtoReflect.Descriptor instead.
func (*CourseRate) Descriptor() ([]byte, []int) {
	return file_attendinfo_proto_rawDescGZIP(), []int{8}
}

func (x *CourseRate) GetCourseMain() uint64 {
	if x != nil {
		return x.CourseMain
	}
	return 0
}

func (x *CourseRate) GetAttendRate() float64 {
	if x != nil {
		return x.AttendRate
	}
	return 0
}

func (x *CourseRate) GetWeek() int32 {
	if x != nil {
		return x.Week
	}
	return 0
}

var File_attendinfo_proto protoreflect.FileDescriptor

var file_attendinfo_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x61, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x70,
	0x0a, 0x11, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x69, 0x64, 0x12,
	0x1f, 0x0a, 0x0b, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x5f, 0x4d, 0x61, 0x69, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x4d, 0x61, 0x69, 0x6e,
	0x22, 0xb5, 0x01, 0x0a, 0x12, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x43, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x41, 0x74, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x61, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x43,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x41, 0x74, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x43, 0x6f,
	0x75, 0x72, 0x73, 0x65, 0x41, 0x74, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xaf, 0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x41, 0x74, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x57, 0x65,
	0x65, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x57, 0x65, 0x65, 0x6b, 0x12, 0x1e,
	0x0a, 0x0a, 0x41, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x52, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0a, 0x41, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x52, 0x61, 0x74, 0x65, 0x12, 0x26,
	0x0a, 0x0e, 0x55, 0x6e, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x55, 0x6e, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e,
	0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x42, 0x0a, 0x0e, 0x55, 0x6e, 0x70, 0x72, 0x65, 0x73,
	0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x61, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x55, 0x6e, 0x70, 0x72,
	0x65, 0x73, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x0e, 0x55, 0x6e, 0x70, 0x72,
	0x65, 0x73, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x58, 0x0a, 0x0e, 0x55, 0x6e,
	0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x4d, 0x69, 0x73, 0x73, 0x41, 0x74, 0x74, 0x65,
	0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x4d, 0x69, 0x73, 0x73, 0x41, 0x74,
	0x74, 0x65, 0x6e, 0x64, 0x22, 0x4e, 0x0a, 0x14, 0x43, 0x6f, 0x75, 0x6e, 0x73, 0x65, 0x6c, 0x6c,
	0x6f, 0x72, 0x41, 0x74, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x36, 0x0a, 0x09,
	0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x61, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x4d, 0x61, 0x6a,
	0x6f, 0x72, 0x52, 0x65, 0x71, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x09, 0x4d, 0x61, 0x6a, 0x6f, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x62, 0x0a, 0x0c, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x52, 0x65, 0x71,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x6e,
	0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6f,
	0x75, 0x73, 0x65, 0x4d, 0x61, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x04, 0x52, 0x09, 0x43,
	0x6f, 0x75, 0x73, 0x65, 0x4d, 0x61, 0x69, 0x6e, 0x22, 0xf5, 0x01, 0x0a, 0x14, 0x43, 0x6f, 0x75,
	0x6e, 0x73, 0x65, 0x6c, 0x6c, 0x6f, 0x72, 0x41, 0x74, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73,
	0x70, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x3b, 0x0a, 0x0d, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x52, 0x61, 0x74, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x74, 0x74,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x52, 0x61, 0x74,
	0x65, 0x52, 0x0d, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x3e, 0x0a, 0x0e, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x74, 0x74, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x61, 0x74, 0x65,
	0x52, 0x0e, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x31, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x32, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x32,
	0x22, 0x41, 0x0a, 0x09, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x52, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4d, 0x61,
	0x6a, 0x6f, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x52, 0x61, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x41, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x52,
	0x61, 0x74, 0x65, 0x22, 0x60, 0x0a, 0x0a, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x61, 0x74,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x4d, 0x61, 0x69, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x4d, 0x61, 0x69,
	0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x52, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x41, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x52, 0x61, 0x74,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x57, 0x65, 0x65, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x57, 0x65, 0x65, 0x6b, 0x32, 0xbb, 0x01, 0x0a, 0x0a, 0x41, 0x74, 0x74, 0x65, 0x6e, 0x64,
	0x69, 0x6e, 0x66, 0x6f, 0x12, 0x51, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73,
	0x65, 0x41, 0x74, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x2e, 0x61, 0x74, 0x74, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x74, 0x74, 0x65, 0x6e, 0x64,
	0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x75, 0x6e, 0x73, 0x65, 0x6c, 0x6c, 0x6f, 0x72, 0x41, 0x74, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x20, 0x2e, 0x61, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x43, 0x6f, 0x75,
	0x6e, 0x73, 0x65, 0x6c, 0x6c, 0x6f, 0x72, 0x41, 0x74, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x1a, 0x20, 0x2e, 0x61, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x43,
	0x6f, 0x75, 0x6e, 0x73, 0x65, 0x6c, 0x6c, 0x6f, 0x72, 0x41, 0x74, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x73, 0x70, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x61, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x66, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_attendinfo_proto_rawDescOnce sync.Once
	file_attendinfo_proto_rawDescData = file_attendinfo_proto_rawDesc
)

func file_attendinfo_proto_rawDescGZIP() []byte {
	file_attendinfo_proto_rawDescOnce.Do(func() {
		file_attendinfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_attendinfo_proto_rawDescData)
	})
	return file_attendinfo_proto_rawDescData
}

var file_attendinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_attendinfo_proto_goTypes = []interface{}{
	(*CourseInfoRequest)(nil),    // 0: attendinfo.CourseInfoRequest
	(*CourseInfoResponse)(nil),   // 1: attendinfo.CourseInfoResponse
	(*CourseAttInfo)(nil),        // 2: attendinfo.CourseAttInfo
	(*UnpresentModel)(nil),       // 3: attendinfo.UnpresentModel
	(*CounsellorAttInfoReq)(nil), // 4: attendinfo.CounsellorAttInfoReq
	(*MajorReqList)(nil),         // 5: attendinfo.MajorReqList
	(*CounsellorAttInfoRsp)(nil), // 6: attendinfo.CounsellorAttInfoRsp
	(*MajorRate)(nil),            // 7: attendinfo.MajorRate
	(*CourseRate)(nil),           // 8: attendinfo.CourseRate
}
var file_attendinfo_proto_depIdxs = []int32{
	2, // 0: attendinfo.CourseInfoResponse.CourseAttInfos:type_name -> attendinfo.CourseAttInfo
	3, // 1: attendinfo.CourseAttInfo.UnpresentInfos:type_name -> attendinfo.UnpresentModel
	5, // 2: attendinfo.CounsellorAttInfoReq.MajorList:type_name -> attendinfo.MajorReqList
	7, // 3: attendinfo.CounsellorAttInfoRsp.MajorRateList:type_name -> attendinfo.MajorRate
	8, // 4: attendinfo.CounsellorAttInfoRsp.CourseRateList:type_name -> attendinfo.CourseRate
	0, // 5: attendinfo.Attendinfo.GetCourseAttInfo:input_type -> attendinfo.CourseInfoRequest
	4, // 6: attendinfo.Attendinfo.GetCounsellorAttInfo:input_type -> attendinfo.CounsellorAttInfoReq
	1, // 7: attendinfo.Attendinfo.GetCourseAttInfo:output_type -> attendinfo.CourseInfoResponse
	6, // 8: attendinfo.Attendinfo.GetCounsellorAttInfo:output_type -> attendinfo.CounsellorAttInfoRsp
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_attendinfo_proto_init() }
func file_attendinfo_proto_init() {
	if File_attendinfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_attendinfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CourseInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_attendinfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CourseInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_attendinfo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CourseAttInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_attendinfo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnpresentModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_attendinfo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CounsellorAttInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_attendinfo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MajorReqList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_attendinfo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CounsellorAttInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_attendinfo_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MajorRate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_attendinfo_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CourseRate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_attendinfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_attendinfo_proto_goTypes,
		DependencyIndexes: file_attendinfo_proto_depIdxs,
		MessageInfos:      file_attendinfo_proto_msgTypes,
	}.Build()
	File_attendinfo_proto = out.File
	file_attendinfo_proto_rawDesc = nil
	file_attendinfo_proto_goTypes = nil
	file_attendinfo_proto_depIdxs = nil
}
